name: ci

on:
    push:
        branches: ["master", "refactor", "refactor-*", "refactor/*"]
        paths:
            [
                "src/**",
                "tests/**",
                "pyproject.toml",
                "requirements.txt",
                "dev.requirements",
            ]
    pull_request:
        branches: ["master", "refactor", "refactor-*", "refactor/*"]
        paths:
            [
                "src/**",
                "tests/**",
                "pyproject.toml",
                "requirements.txt",
                "dev.requirements",
            ]

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    test-3-9:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest -vv

    test-3-10:
        needs: test-3-9

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest -vv

    test-3-11:
        needs: test-3-10

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest -vv

    test-3-12:
        needs: test-3-11

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest -vv

    test-3-13:
        needs: test-3-12

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.13
              uses: actions/setup-python@v3
              with:
                  python-version: "3.13"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest -vv

    pip-install-3-9:
        needs: test-3-9

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .

    pip-install-3-10:
        needs:
            - test-3-10
            - pip-install-3-9

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .

    pip-install-3-11:
        needs:
            - test-3-11
            - pip-install-3-10

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .

    pip-install-3-12:
        needs:
            - test-3-12
            - pip-install-3-11

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .

    pip-install-3-13:
        needs:
            - test-3-13
            - pip-install-3-12

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.13
              uses: actions/setup-python@v3
              with:
                  python-version: "3.13"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .
