name: docs

on:
    push:
        branches: ["master"]
        paths: ["docs/**", ".github/workflows/docs.yml"]
    pull_request:
        branches: ["master"]
        paths: ["docs/**", ".github/workflows/docs.yml"]

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable

            - name: Restore Cargo Cache
              id: restore_cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install mdbook
              if: steps.restore_cache.outputs.cache-hit != 'true'
              run: cargo install --git https://github.com/rust-lang/mdBook.git mdbook

            - name: Build docs
              run: bash ./scripts/docs/build.sh

            - uses: actions/cache@v4
              if: steps.restore_cache.outputs.cache-hit != 'true'
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
