name: ci

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    test-3-10:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            max-parallel: 1
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt
                  pip install .

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest

    test-3-11:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            max-parallel: 1
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11"
            - name: Setup Venv
              run: |
                  python -m venv ./venv

            - name: Install packages
              run: |
                  source ./venv/bin/activate
                  pip install -r dev.requirements
                  pip install -r requirements.txt
                  pip install .

            - name: Run tests
              run: |
                  source ./venv/bin/activate
                  pytest

    pip-install-3-10:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            max-parallel: 1
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .

    pip-install-3-11:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            max-parallel: 1
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r dev.requirements
            - name: Install build deps
              run: python3 -m pip install --upgrade build
            - name: Build
              run: python3 -m build
            - name: Install
              run: python3 -m pip install .
